en:
    cancel: Cancel
    code: "Code:"
    consultations: Consultations
    consultations-count: "Consultations:"
    create-stat: Create Statistics
    create-stat-consultation: Consult. Statistics
    create-stat-patient: Patients Statistics
    date-min: Start Date
    date-max: End Date
    logout: Logout
    patients: Patients
    patients-count: "Patients:"
    struct: "Structure:"
fr:
    cancel: Annuler
    code: "Code :"
    consultations: Consultations
    consultations-count: "Consultations :"
    create-stat: Créer des statistiques
    create-stat-consultation: Stats consultations
    create-stat-patient: Stats patients
    date-min: Date de début
    date-max: Date de fin
    logout: Déconnexion
    patients: Patients
    patients-count: "Patients :"
    struct: "Structure :"
