en:
    cancel: Cancel
    close: Close
    code: "Code:"
    consultations: Consultations
    consultations-count: "Consultations:"
    create-stat: Create Statistics
    create-stat-consultation: Consult. Statistics
    create-stat-patient: Patients Statistics
    date-min: Start Date
    date-max: End Date
    logout: Logout
    patients: Patients
    patients-count: "Patients:"
    stat-type: "Statistic Type"
    struct: "Structure:"
    welcome: "To add new statistics, clic on the left pane's button bearing the following icon:"
fr:
    cancel: Annuler
    close: Fermer
    code: "Code :"
    consultations: Consultations
    consultations-count: "Consultations :"
    create-stat: Créer des statistiques
    create-stat-consultation: Stats consultations
    create-stat-patient: Stats patients
    date-min: Date de début
    date-max: Date de fin
    logout: Déconnexion
    patients: Patients
    patients-count: "Patients :"
    stat-type: "Type de statistique"
    struct: "Structure :"
    welcome: "Pour ajouter des statistiques, cliquez sur le bouton avec l'icône suivante dans le panneau de gauche : "
